### ISSUE TITLE
Remove SynonymousTo attribute usage

### ISSUE THREAD

**Issue by miyconst** [StarcounterApps/Simplified#95] opened 2017-12-07 11:55 UTC
The `[SynonymousTo]`  attribute for the database classes is deprecated and going to be removed in the next major Starcounter release.

**Comment by miyconst** [comment] 2017-12-07 11:55
https://github.com/StarcounterApps/Simplified/search?utf8=%E2%9C%93&q=SynonymousTo&type=

**Comment by per-samuelsson** [comment] 2017-12-07 13:26
Cheat sheet (raw material): https://github.com/per-samuelsson/Misc/issues/6#issuecomment-349963169

**Comment by miyconst** [comment] 2017-12-07 15:05
Pull request is here - https://github.com/StarcounterApps/Simplified/pull/96.

**Comment by miyconst** [comment] 2017-12-08 07:48
Branch for `2.4` - [issues/95-remove-synonymous-to-v2.4](https://github.com/StarcounterApps/Simplified/tree/issues/95-remove-synonymous-to-v2.4).

**Comment by miyconst** [comment] 2017-12-09 23:19
Done. Merged into `master` and `master-v2.4`.

**Comment by LarsTjernstrom** [comment] 2017-12-10 15:03
Since the apps team are now supporting 3 versions of the prefab apps, 2.3, 2.4 with Simplified and 2.4 based on local db models and mapping and we have a real delivery to a customer. So we have our hands full, so I ask you, why are we depricating functionality at all? There must be a really good reason? We want to add functionality, e.g. authentication and authorization to the apps, but we are spending most of our time just refactoring the apps, to keep them up and running.

**Comment by miyconst** [comment] 2017-12-10 15:07
@LarsTjernstrom the decision to deprecated `[SynonymousTo]` was made long ago, and I didn't spend time from the apps team members, only @Mihaiii helped with a pull request review.

This deprecation does not remove anything from the apps or simplified, since the behavior of simplified is not changed, it is just implemented with standard .net features.

What extra do you want to see in scope of this issue by reopening it?

**Comment by LarsTjernstrom** [comment] 2017-12-11 08:07
@miyconst The reason for reopening was Habibs comment below. But we can close it again, since I've gone through the refactoring of Simplified and you didn't do any changes to 
_Something a = SomebodiesRelation.WhatIs;_

Still, what is the actual reason for obsoleting the SynonymousTo attribute? Because every feature that we obsolete will lead to refactoring internally and for our partners (=delivery time will increase and important things as failover, backup will be postponed).

_”Looks like there is no way to make a central change, will have to update all the apps.”
Before
var relation=new SomebodiesRelation();
var whatIs = relation.WhatIs;

After
var relation=new SomebodiesRelation();
var whatIs = relation.WhoIs as Something;_

**Closed by LarsTjernstrom** 2017-12-11 08:07 UTC

**Comment by per-samuelsson** [comment] 2017-12-11 08:17
@LarsTjernstrom 

I see your point. But we come from a looooooong stretch of constant, furious (and often not well-grounded) adding of features, just years and years of adding new stuff people have been screaming loudest about basically.

I believe that at some point, we need short iterations where we go through stuff from the past not in use any more (and/or with bad design), and try to get away from maintaining them in the long run. This is one of those things.

If we had decided to instead keep this feature, we had to start properly write documentation for it, add proper regression testing for it, and also - maybe more important - make sure it also work flawless **in combination with everything else we have planned for**. Like, for instance, mapping.

IMO, sometimes removing features is a long-term improvement to any product. I think this was one of them.

**Comment by per-samuelsson** [comment] 2017-12-11 08:21
Whats that comment from:

> ”Looks like there is no way to make a central change, will have to update all the apps.

?

That should not be the effect of us removing support for synonyms. Then it was done wrong. Everything that could be done with synonyms is easily replaceable with standard .NET features (i.e. explicitly computed properties), or else it's done wrong.

**Comment by miyconst** [comment] 2017-12-11 10:03
Adding to what @per-samuelsson has already said.

>”Looks like there is no way to make a central change, will have to update all the apps.”
Before

```cs
var relation=new SomebodiesRelation();
var whatIs = relation.WhatIs;
```

After

```cs
var relation=new SomebodiesRelation();
var whatIs = relation.WhoIs as Something;
```

That was a wrong assumption by @habib535. The apps do not need to get changed at all, refactored version of Simplified is fully compatible with the apps, only source code recompilation is required.

>IMO, sometimes removing features is a long-term improvement to any product. I think this was one of them.

If fact, this is an immediate investment. 

- We already use mapping, and `SynonymousTo` is not supported there. 
- Next generation weaver is under development and one less redundant feature means less human (@per-samuelsson)-hours spent.
- `SynonymousTo` throws `InvalidCastException` when the base property contains a value which can't be cast  to the synonymous type.

And a `p.s.`, if I would not get bothered with `SynonymousTo` removal, the `master-v2.4` branch of Simplified would keep staying far behind the main `master` branch, and this is where the apps team members spend the most of the time, merging already existing work from `master` to `master-v2.4`.
